alias python='python3'
alias work='cd /home/ubuntu/mercury/websrc/src/villapp && source /home/ubuntu/mercury/websrc/villapp_env/bin/activate'
alias sbrc='source ~/.bashrc'
alias aenv='source /home/ubuntu/mercury/websrc/villapp_env/bin/activate'
alias djrk='cd /home/ubuntu/mercury/websrc/src/villapp'
alias rds='python /home/ubuntu/mercury/websrc/src/villapp/manage.py runserver 0.0.0.0:9002'
